// Original design fixtures, imported once by the explicitly local development seed.
export const seedDashboard = {
  activeRequests: 4,
  newBids: 12,
  unreadMessages: 3,
  requests: [
    {
      id: "R-8924",
      title: "Weekly homemade Italian dinners for 4",
      category: "Food & meal prep",
      status: "ready",
      statusLabel: "Ready to compare",
      bidCount: 3,
      posted: "Posted 2 days ago",
      deadline: "Respond by Sep 9, 6:00 PM",
      neighborhood: "South Congress · Austin, TX",
      budget: "$120–$180 per delivery",
      bids: [
        {
          id: "bid-maria",
          seller: "Chef Maria L.",
          initials: "ML",
          rating: 4.9,
          reviews: 128,
          pricePerDelivery: 145,
          totalPrice: 1160,
          deliveryCount: 8,
          cadence: "Tuesday / Thursday",
          earliestStart: "September 14",
          distance: 2.1,
          summary: "Sicilian family recipes, grocery sourcing, and cleanup included.",
          proposal: "I’ll create two family-style Italian dinners each week, sized for four adults. Every delivery includes a seasonal salad, main dish, reheating notes, ingredient list, and full grocery sourcing. I can accommodate one vegetarian dinner per week with 48 hours notice.",
          fitReason: "Best balance of rating, proximity, and schedule match.",
          recommended: true,
          status: "active",
        },
        {
          id: "bid-tuscany",
          seller: "Taste of Tuscany",
          initials: "TT",
          rating: 4.7,
          reviews: 84,
          pricePerDelivery: 120,
          totalPrice: 960,
          deliveryCount: 8,
          cadence: "Wednesday / Friday",
          earliestStart: "September 20",
          distance: 5.4,
          summary: "Family-style drop-off meals with simple reheating and minimal prep.",
          proposal: "Our four-week plan includes eight rotating Tuscan-inspired meals with bread and salad. Meals arrive chilled in returnable containers. Our fixed Wednesday and Friday route keeps the price lean, and menu substitutions are available for allergies.",
          status: "active",
        },
        {
          id: "bid-canvas",
          seller: "Culinary Canvas",
          initials: "CC",
          rating: 5,
          reviews: 212,
          pricePerDelivery: 210,
          totalPrice: 1680,
          deliveryCount: 8,
          cadence: "Flexible",
          earliestStart: "September 12",
          distance: 1.2,
          summary: "Highly customized private-chef menus with optional wine pairings.",
          proposal: "I’ll design a bespoke four-week menu after a short preference call. Service includes premium ingredients, reusable packaging, flexible delivery windows, and optional pairing notes. Two menu revisions are included before the first delivery.",
          status: "active",
        },
      ],
    },
    {
      id: "R-8917",
      title: "Biweekly native garden maintenance",
      category: "Home services",
      status: "collecting",
      statusLabel: "Collecting bids",
      bidCount: 2,
      posted: "Posted yesterday",
      deadline: "Bidding closes Sep 11",
      neighborhood: "Bouldin Creek · Austin, TX",
      budget: "$90–$140 per visit",
      bids: [],
    },
    {
      id: "R-8898",
      title: "Algebra II tutor for a tenth grader",
      category: "Tutoring",
      status: "collecting",
      statusLabel: "Collecting bids",
      bidCount: 0,
      posted: "Posted 4 hours ago",
      deadline: "Bidding closes Sep 12",
      neighborhood: "Travis Heights · Austin, TX",
      budget: "$40–$65 per session",
      bids: [],
    },
    {
      id: "R-8821",
      title: "Custom oak entryway bench",
      category: "Furniture",
      status: "completed",
      statusLabel: "Completed",
      bidCount: 5,
      posted: "Posted Aug 12",
      deadline: "Completed Aug 31",
      neighborhood: "Zilker · Austin, TX",
      budget: "$700–$1,100 total",
      acceptedSeller: "Eastside Joinery",
      bids: [],
    },
  ],
}

export const seedWorkspace = {
  currentUser: { id: "buyer-jordan", initials: "JL", name: "Jordan Lee" },
  unreadCount: 3,
  conversations: [
    {
      id: "conversation-maria",
      participant: {
        id: "seller-maria",
        initials: "ML",
        name: "Chef Maria L.",
        responseNote: "Usually replies within an hour",
        role: "Verified meal-prep seller",
        verified: true,
      },
      requestTitle: "Weekly homemade Italian dinners",
      preview: "I put together next week’s menu.",
      updatedAt: "10:42 AM",
      unreadCount: 0,
      status: "active",
      proposal: {
        id: "proposal-maria",
        requestId: "R-8924",
        title: "Weekly homemade Italian dinners",
        status: "accepted",
        rate: "$68 per delivery",
        quantity: "4 portions",
        schedule: "Wednesdays · 6:30 PM",
        location: "Hyde Park · Austin",
        dietary: "No shellfish",
        milestone: {
          confirmed: false,
          date: "Wednesday · Sep 9",
          time: "6:30 PM",
          location: "Hyde Park",
        },
      },
      messages: [
        {
          id: "message-maria-1",
          author: "seller",
          body: "Hi Jordan — I’ve put together a proposed menu for next week based on your preferences. Let me know what you think.",
          sentAt: "10:42 AM",
          status: "sent",
          attachment: {
            id: "attachment-menu",
            name: "Menu_Proposal_Sept_W2.pdf",
            size: "1.2 MB",
            type: "document",
          },
        },
        {
          id: "message-jordan-1",
          author: "buyer",
          body: "This looks fantastic, Maria. The truffle risotto sounds amazing. We’re good to go for Wednesday.",
          sentAt: "10:45 AM",
          status: "sent",
        },
      ],
    },
    {
      id: "conversation-lawn",
      participant: {
        id: "seller-green-thumb",
        initials: "GT",
        name: "Green Thumb Pros",
        responseNote: "Usually replies the same day",
        role: "Verified garden-care team",
        verified: true,
      },
      requestTitle: "Biweekly native garden maintenance",
      preview: "The yard looks ready for the fall trim.",
      updatedAt: "Yesterday",
      unreadCount: 2,
      status: "active",
      proposal: {
        id: "proposal-lawn",
        requestId: "R-8917",
        title: "Biweekly native garden maintenance",
        status: "active",
        rate: "$112 per visit",
        quantity: "Front and back garden",
        schedule: "Every other Friday",
        location: "Bouldin Creek · Austin",
        dietary: "Native plants only",
      },
      messages: [
        {
          id: "message-lawn-1",
          author: "seller",
          body: "The yard looks ready for the fall trim. I can send a short care plan before we begin.",
          sentAt: "Yesterday",
          status: "sent",
        },
      ],
    },
    {
      id: "conversation-tutor",
      participant: {
        id: "seller-chen",
        initials: "AC",
        name: "Dr. A. Chen",
        responseNote: "Usually replies within two hours",
        role: "Verified mathematics tutor",
        verified: true,
      },
      requestTitle: "Calculus tutoring for a college freshman",
      preview: "Here are the notes from our first session.",
      updatedAt: "Tue",
      unreadCount: 1,
      status: "active",
      proposal: {
        id: "proposal-tutor",
        requestId: "R-8898",
        title: "Weekly calculus tutoring",
        status: "active",
        rate: "$58 per session",
        quantity: "60 minutes",
        schedule: "Tuesdays · 5:00 PM",
        location: "Travis Heights · Austin",
        dietary: "In-person sessions",
      },
      messages: [
        {
          id: "message-tutor-1",
          author: "seller",
          body: "Here are the notes from our first session. The practice set focuses on limits and continuity.",
          sentAt: "Tue · 6:12 PM",
          status: "sent",
        },
      ],
    },
  ],
}

export const seedOpportunity = {
  slug: "east-austin-team-lunch",
  title: "Weekday lunch delivery for creative offices in East Austin.",
  category: "Food & meal prep",
  location: "East Austin · within 3.1 miles",
  verifiedLabel: "Verified demand cluster",
  requestCount: 28,
  organizationCount: 14,
  weeklyValue: "$2.4k",
  description:
    "Aggregated demand from 14 independent studios, agencies, and technology teams seeking dependable, high-quality, sustainably packaged weekday lunches.",
  metrics: [
    { label: "Volume", value: "146", detail: "meals per week" },
    { label: "Median budget", value: "$17", detail: "per meal" },
    { label: "Service area", value: "3.1", detail: "mile radius" },
    { label: "Peak days", value: "T–Th", detail: "highest volume" },
    { label: "Schedule overlap", value: "82%", detail: "delivery windows" },
  ],
  timeline: [
    { label: "Week 1", requests: 5 },
    { label: "Week 2", requests: 9 },
    { label: "Week 3", requests: 11 },
    { label: "Week 4", requests: 21 },
    { label: "Week 5", requests: 16 },
    { label: "Current", requests: 25 },
  ],
  neighborhoods: [
    { id: "east-cesar-chavez", name: "East Cesar Chavez", share: 42, requests: 12, meals: 62, insight: "The densest cluster, led by teams of 8–16 ordering twice weekly." },
    { id: "holly", name: "Holly", share: 28, requests: 8, meals: 41, insight: "Strong reusable-packaging preference and the tightest noon delivery window." },
    { id: "govalle", name: "Govalle", share: 18, requests: 5, meals: 27, insight: "Smaller teams with the highest vegetarian and gluten-free overlap." },
    { id: "mueller", name: "Mueller", share: 12, requests: 3, meals: 16, insight: "Emerging demand from hybrid teams concentrated on Wednesdays." },
  ],
  excerpts: [
    { id: "excerpt-1", neighborhoodId: "east-cesar-chavez", quote: "A healthy office lunch for 12 that arrives ready to serve every Tuesday and Thursday.", organization: "Independent design studio", cadence: "2× weekly" },
    { id: "excerpt-2", neighborhoodId: "holly", quote: "Gluten-free and vegetarian choices in returnable containers for our product team.", organization: "Technology agency", cadence: "Weekly" },
    { id: "excerpt-3", neighborhoodId: "govalle", quote: "Fresh salads and one warm option for a rotating studio team of eight to fourteen.", organization: "Architecture practice", cadence: "3× weekly" },
  ],
  evidence: [
    { label: "Sample size", value: "28", detail: "matched requests", explanation: "Only active requests sharing category, service radius, quantity, and delivery timing are included." },
    { label: "Freshness", value: "24", detail: "in the last 21 days", explanation: "Recent requests receive more weight so sellers see current purchasing intent." },
    { label: "Repeat intent", value: "71%", detail: "recurring potential", explanation: "Twenty buyers explicitly asked for a weekly or multi-week arrangement." },
    { label: "Schedule overlap", value: "82%", detail: "delivery alignment", explanation: "Most requested windows overlap between 11:30 AM and 12:30 PM Tuesday through Thursday." },
  ],
  requirements: [
    { label: "Dietary requirements", value: "Vegetarian, nut-free, gluten-free" },
    { label: "Packaging preference", value: "Reusable or returnable containers" },
    { label: "Delivery window", value: "11:30 AM–12:30 PM" },
  ],
  readiness: [
    "Weekday production capacity",
    "Delivery within 3.1 miles",
    "Reusable container logistics",
    "Dietary labeling capability",
  ],
  saved: false,
  refreshedAt: "Updated 18 minutes ago",
}

