"use client"

import Link from "next/link"
import { useState } from "react"
import { ArrowRight, MapPin } from "lucide-react"
import { SiteHeader } from "@/components/site-header"
import { MarketplaceState } from "@/components/marketplace-state"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { useMarketplaceRequests, useMarketplaceOpportunities } from "@/lib/marketplace-data"

export function PersistentDemand() {
  const query = useMarketplaceRequests()
  const opportunities = useMarketplaceOpportunities()
  const [category, setCategory] = useState("all")
  const [search, setSearch] = useState("")
  const [sort, setSort] = useState("newest")
  if (query.isPending) return <MarketplaceState loading title="Finding the demand…" message="Loading published requests from the marketplace." />
  if (query.isError || !query.data) return <MarketplaceState title="Demand unavailable" message={query.error?.message ?? "Requests could not be loaded."} retry={() => void query.refetch()} />
  const requests = query.data.requests
  const categories = [...new Set(requests.map((request) => request.category))].sort()
  const visible = requests.filter((request) => (category === "all" || request.category === category) && `${request.title} ${request.description} ${request.zip} ${request.locationArea}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => sort === "budget" ? b.budgetMax - a.budgetMax : new Date(b.createdAt).valueOf() - new Date(a.createdAt).valueOf())
  const areas = [...new Set(visible.map((request) => request.zip))]
  return <main className="min-h-svh bg-background"><SiteHeader active="demand" variant="app" />
    <section className="border-b border-divider bg-white" id="content" tabIndex={-1}><div className="mx-auto max-w-[1440px] px-5 py-12 md:px-10 lg:px-16"><p className="eyebrow text-ember-ink">Demand, made visible</p><h1 className="mt-4 font-display text-[clamp(2.8rem,6vw,5.5rem)] font-semibold leading-tight tracking-[-0.06em]">See what people need.</h1><p className="mt-4 text-subtle">{requests.length} open requests · {categories.length} categories · Approximate ZIP-code areas</p><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-[1fr_240px_200px]"><label className="grid gap-2 text-xs font-semibold" htmlFor="demand-search">Search requests or ZIP code<Input id="demand-search" type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Try meals, lawn care, or 78704" /></label><label className="grid gap-2 text-xs font-semibold" htmlFor="demand-category">Category<select id="demand-category" className="min-h-12 rounded-lg border border-divider bg-white px-4 text-base" value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">All categories</option>{categories.map((value) => <option value={value} key={value}>{value}</option>)}</select></label><label className="grid gap-2 text-xs font-semibold" htmlFor="demand-sort">Sort by<select id="demand-sort" className="min-h-12 rounded-lg border border-divider bg-white px-4 text-base" value={sort} onChange={(event) => setSort(event.target.value)}><option value="newest">Newest first</option><option value="budget">Highest budget</option></select></label></div></div></section>
    <div className="mx-auto grid max-w-[1440px] gap-8 px-5 py-10 md:px-10 lg:grid-cols-[1fr_340px] lg:px-16"><section aria-label="Matching requests"><div className="mb-5 flex items-center justify-between gap-4"><h2 className="font-display text-2xl font-semibold">Open requests</h2><p className="text-sm text-subtle" role="status">{visible.length} results</p></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-1 xl:grid-cols-2">{visible.map((request) => <article className="enterprise-panel flex flex-col p-6" key={request.id}><p className="eyebrow text-ember-ink">{request.category}</p><h3 className="mt-4 break-words text-xl font-semibold">{request.title}</h3><p className="mt-4 line-clamp-3 break-words text-sm leading-6 text-subtle">{request.description}</p><p className="mt-5 flex items-center gap-2 text-sm text-subtle"><MapPin className="size-4 shrink-0" aria-hidden="true" />{request.locationArea} · {request.zip}</p><p className="mt-3 font-semibold">${request.budgetMin.toLocaleString()}–${request.budgetMax.toLocaleString()} <span className="text-sm font-normal text-subtle">· {request.frequency}</span></p><Button asChild className="mt-6 self-start" variant="outline"><Link href={`/requests/${request.id}`}>Review request <ArrowRight className="size-4" aria-hidden="true" /></Link></Button></article>)}</div>{!visible.length ? <div className="enterprise-panel p-8"><h3 className="text-xl font-semibold">No requests match yet.</h3><p className="mt-3 text-subtle">Try a different search or publish the first request in your area.</p><Button asChild className="mt-6" variant="ember"><Link href="/requests/new">Post a request</Link></Button></div> : null}</section>
      <aside className="space-y-6"><section className="rounded-xl bg-black p-6 text-white"><p className="eyebrow text-white/60">Area overview</p><h2 className="mt-4 font-display text-3xl font-semibold tracking-tight">Local demand signals.</h2><p className="mt-4 text-sm leading-6 text-white/60">Counts below reflect matching requests by ZIP code, not precise addresses or map coordinates.</p><dl className="mt-6 divide-y divide-white/20">{areas.map((zip) => <div className="flex justify-between gap-4 py-4" key={zip}><dt>ZIP {zip}</dt><dd className="font-semibold">{visible.filter((request) => request.zip === zip).length} requests</dd></div>)}</dl></section><section className="enterprise-panel p-6"><h2 className="font-display text-2xl font-semibold">Opportunity briefs</h2><p className="mt-3 text-sm text-subtle">Saved research briefs are separate from the live request counts above.</p>{opportunities.data?.opportunities.map((opportunity) => <Link className="mt-5 block border-t border-divider pt-5 font-semibold underline underline-offset-4" key={opportunity.slug} href={`/opportunities/${opportunity.slug}`}>{opportunity.title}</Link>)}{opportunities.isError ? <p className="mt-4 text-sm text-error">Briefs could not be loaded. <button className="min-h-11 underline" onClick={() => void opportunities.refetch()}>Retry</button></p> : null}{opportunities.data?.opportunities.length === 0 ? <p className="mt-4 text-sm text-subtle">No briefs published yet.</p> : null}</section></aside>
    </div></main>
}
