"use client"

import Link from "next/link"
import { useState } from "react"
import { ArrowRight, MessageCircle } from "lucide-react"
import { MarketplaceState } from "@/components/marketplace-state"
import { SiteHeader } from "@/components/site-header"
import { Button } from "@/components/ui/button"
import { useMarketplaceSeller } from "@/lib/marketplace-data"

export function PersistentSellerWorkspace({ view, bidId }: { view: "dashboard" | "bid" | "test-plan"; bidId?: string }) {
  const query = useMarketplaceSeller()
  const [filter, setFilter] = useState("all")
  if (query.isPending) return <MarketplaceState loading title="Opening your seller workspace…" message="Loading saved proposals and current requests." />
  if (query.isError || !query.data) return <MarketplaceState title="Seller workspace unavailable" message={query.error?.message ?? "Your data could not be loaded."} retry={() => void query.refetch()} />
  const data = query.data
  const selected = data.bids.find((bid) => bid.id === bidId)
  const bids = data.bids.filter((bid) => filter === "all" || bid.status === filter)
  const active = data.bids.filter((bid) => bid.status === "active")
  const accepted = data.bids.filter((bid) => bid.status === "accepted")
  const currency = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value)
  return <main className="min-h-svh bg-background">
    <SiteHeader active="seller" messageCount={data.unreadMessages} variant="app" />
    <section className="border-b border-divider bg-white" id="content" tabIndex={-1}><div className="mx-auto flex max-w-[1440px] flex-wrap items-end justify-between gap-6 px-5 py-12 md:px-10 lg:px-16"><div><p className="eyebrow text-ember-ink">Seller workspace</p><h1 className="mt-4 font-display text-[clamp(2.7rem,5vw,5rem)] font-semibold leading-tight tracking-[-0.06em]">Build on real demand.</h1><p className="mt-4 text-subtle">{data.currentUser.name} · Your saved proposals and local opportunities.</p></div><div className="flex gap-3"><Button asChild variant="outline"><Link href="/buyer">Buyer workspace</Link></Button><Button asChild variant="ember"><Link href="/demand">Find requests <ArrowRight className="size-4" aria-hidden="true" /></Link></Button></div></div></section>
    <section className="bg-black text-white"><dl className="mx-auto grid max-w-[1440px] grid-cols-2 md:grid-cols-4 lg:px-12">{[[currency(active.reduce((sum, bid) => sum + bid.totalPrice, 0)), "Active proposal value"], [String(active.length), "Active bids"], [String(accepted.length), "Accepted bids"], [String(data.unreadMessages), "Unread messages"]].map(([value, label]) => <div className="border-r border-white/15 px-5 py-8" key={label}><dt className="text-xs uppercase tracking-wider text-white/60">{label}</dt><dd className="mt-3 font-display text-4xl font-semibold tracking-tight">{value}</dd></div>)}</dl></section>
    <div className="mx-auto max-w-[1440px] space-y-10 px-5 py-10 md:px-10 lg:px-16">
      {view === "bid" ? <section className="enterprise-panel p-6 md:p-8"><p className="eyebrow text-subtle">Proposal detail</p><h2 className="mt-3 break-words font-display text-3xl font-semibold">{selected?.requestTitle ?? "Proposal not found"}</h2>{selected ? <><p className="mt-4 text-subtle">{selected.id} · {selected.status} · {currency(selected.pricePerDelivery)} per delivery · {selected.deliveryCount} deliveries</p><p className="mt-5 whitespace-pre-wrap break-words leading-7">{selected.proposal}</p><p className="mt-4 text-sm text-subtle">{selected.cadence} · Earliest start {selected.earliestStart}</p><div className="mt-6 flex flex-wrap gap-3"><Button asChild variant="outline"><Link href={`/requests/${selected.requestId}`}>View request</Link></Button>{selected.conversationId ? <Button asChild><Link href={`/messages?role=seller&conversation=${encodeURIComponent(selected.conversationId)}`}>Open conversation</Link></Button> : null}</div></> : <p className="mt-4 text-subtle">This proposal is not part of your seller workspace. Choose one below.</p>}</section> : null}
      <section className="enterprise-panel overflow-hidden"><div className="flex flex-wrap items-end justify-between gap-5 border-b border-divider p-6"><div><p className="eyebrow text-subtle">Pipeline</p><h2 className="mt-2 font-display text-3xl font-semibold tracking-tight">Your proposals</h2></div><label className="grid gap-2 text-xs font-semibold" htmlFor="seller-bid-filter">Status<select className="min-h-11 rounded-lg border border-divider bg-white px-4 text-sm" id="seller-bid-filter" value={filter} onChange={(event) => setFilter(event.target.value)}>{["all", "active", "accepted", "declined"].map((value) => <option key={value} value={value}>{value.charAt(0).toUpperCase() + value.slice(1)}</option>)}</select></label></div><div className="divide-y divide-divider">{bids.length ? bids.map((bid) => <article className="flex flex-wrap items-center justify-between gap-5 p-6" key={bid.id}><div className="min-w-0"><p className="eyebrow text-ember-ink">{bid.status} · {bid.id}</p><h3 className="mt-3 break-words text-xl font-semibold">{bid.requestTitle}</h3><p className="mt-2 text-sm text-subtle">{currency(bid.totalPrice)} total · {bid.cadence}</p></div><div className="flex flex-wrap gap-3"><Button asChild variant="outline"><Link href={`/seller/bids/${bid.id}`}>View proposal</Link></Button>{bid.conversationId ? <Button asChild variant="ghost"><Link href={`/messages?role=seller&conversation=${encodeURIComponent(bid.conversationId)}`}><MessageCircle className="size-4" aria-hidden="true" />Message buyer</Link></Button> : null}</div></article>) : <p className="p-8 text-subtle">No {filter === "all" ? "" : filter + " "}proposals yet. Open a request below and send your first offer.</p>}</div></section>
      <section><div className="flex flex-wrap items-center justify-between gap-4"><h2 className="font-display text-3xl font-semibold tracking-tight">Open requests</h2><Button asChild variant="ghost"><Link href="/demand">Browse all <ArrowRight className="size-4" aria-hidden="true" /></Link></Button></div><div className="mt-6 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{data.requests.filter((request) => request.status === "open").slice(0, 6).map((request) => <article className="enterprise-panel flex flex-col p-6" key={request.id}><p className="eyebrow text-ember-ink">{request.category}</p><h3 className="mt-4 break-words text-xl font-semibold">{request.title}</h3><p className="mt-3 text-sm text-subtle">{request.locationArea} · ZIP {request.zip}</p><p className="mt-4 font-semibold">{currency(request.budgetMin)}–{currency(request.budgetMax)}</p><Button asChild className="mt-6 self-start" variant="outline"><Link href={`/requests/${request.id}`}>Review &amp; bid</Link></Button></article>)}</div>{!data.requests.some((request) => request.status === "open") ? <p className="mt-5 text-subtle">No open requests right now. New buyer requests will appear here.</p> : null}</section>
      <section className="grid gap-6 lg:grid-cols-2"><div className="enterprise-panel p-6"><h2 className="font-display text-2xl font-semibold">Saved opportunities</h2><div className="mt-5 divide-y divide-divider">{data.savedOpportunities.map((opportunity) => <Link className="block py-4 font-semibold underline underline-offset-4" href={`/opportunities/${opportunity.slug}`} key={opportunity.slug}>{opportunity.title}</Link>)}{!data.savedOpportunities.length ? <p className="text-sm text-subtle">Bookmark an opportunity to keep it here.</p> : null}</div></div><div className="enterprise-panel p-6"><h2 className="font-display text-2xl font-semibold">Offer drafts</h2><p className="mt-3 text-sm text-subtle">Saved planning drafts. These are not published bids.</p>{data.offerDrafts.map((draft) => <div className="mt-5 border-t border-divider pt-5" key={draft.draftId}><Link className="font-semibold underline underline-offset-4" href={`/opportunities/${draft.slug}`}>{draft.slug.replaceAll("-", " ")}</Link><p className="mt-2 text-sm">{currency(draft.pricePerMeal)} per meal · {draft.weeklyCapacity} weekly capacity</p><p className="mt-2 break-words text-sm text-subtle">{draft.note}</p></div>)}{!data.offerDrafts.length ? <p className="mt-5 text-sm text-subtle">Create an offer draft from an opportunity to start planning.</p> : null}</div></section>
    </div>
  </main>
}
